"""
A format-neutral model of a document's *structure* (headings, paragraphs,
lists, tables, figures), plus the facts accessibility checks need (title,
language, existing alt text, table header rows).

Extractors for DOCX, PPTX (and later PDF) fill this in; the accessibility
checks in a11y_checks.py and the reading-text generator below both work from
it, so every format gets the same treatment.

Every piece of text/alt text carries a `source` -- "original" (in the file as
authored), "machine" (generated by a model) or "human" (a person wrote or
approved it) -- so machine output can always be labelled as such and revised.
"""

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

ORIGINAL, MACHINE, HUMAN = "original", "machine", "human"

# Block kinds
HEADING, SLIDE_TITLE, PARAGRAPH, LIST_ITEM, TABLE, FIGURE, NOTE = (
    "heading", "slide_title", "paragraph", "list_item", "table", "figure", "note")


@dataclass
class Block:
    kind: str
    text: str = ""
    level: int = 0                      # heading level (1-9) or list depth
    location: str = ""                  # human-readable, e.g. "Slide 3" or "Paragraph 14"
    # figures
    figure_type: str = ""               # picture | chart | diagram | media | textbox-drawing
    name: str = ""                      # file/shape name (often a meaningless "Picture 3")
    alt_text: str = ""
    alt_source: str = ORIGINAL
    decorative: bool = False
    # tables
    rows: List[List[str]] = field(default_factory=list)
    header_row: bool = False
    # misc
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DocumentStructure:
    format: str                         # docx | pptx | pdf
    title: str = ""
    language: str = ""
    blocks: List[Block] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_text(self) -> str:
        """Plain reading text (what the RSVP reader and text-to-speech consume)."""
        out: List[str] = []
        for b in self.blocks:
            if b.kind in (HEADING, SLIDE_TITLE, PARAGRAPH, LIST_ITEM, NOTE):
                if b.text.strip():
                    out.append(b.text.strip())
            elif b.kind == TABLE:
                rows = [" , ".join(c.strip() for c in r if c.strip()) for r in b.rows]
                rows = [r for r in rows if r]
                if rows:
                    out.append("Table. " + ". ".join(rows) + ".")
            elif b.kind == FIGURE:
                if b.alt_text.strip() and not b.decorative:
                    out.append(f"Image: {b.alt_text.strip()}")
        return "\n\n".join(out)

    def headings(self) -> List[Block]:
        return [b for b in self.blocks if b.kind == HEADING]

    def figures(self) -> List[Block]:
        return [b for b in self.blocks if b.kind == FIGURE]

    def tables(self) -> List[Block]:
        return [b for b in self.blocks if b.kind == TABLE]
