#!/bin/bash
# Regenerates THIRD_PARTY_LICENSES/THIRD_PARTY_NOTICES.md from the real package
# metadata of what ships: the backend image's Python packages and the
# frontend's production npm packages. Needs Docker. Re-run when dependencies
# change (and before a release) so the notice never drifts from reality.
set -euo pipefail
cd "$(dirname "$0")/.."
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

echo "[1/3] Python packages (builds the backend image)..."
docker build -q -f backend/Dockerfile -t webreader-notices . >/dev/null
docker run --rm webreader-notices sh -c \
  'pip install -q pip-licenses >/dev/null 2>&1; pip-licenses --format=csv --with-urls --with-system --ignore-packages pip-licenses prettytable 2>/dev/null' \
  > "$TMP/py.csv"

echo "[2/3] npm packages..."
docker run --rm -v "$PWD/frontend:/app" -w /app -u "$(id -u):$(id -g)" -e HOME=/tmp node:22-alpine \
  sh -c 'npm ci --silent >/dev/null 2>&1; npx --yes license-checker --production --json 2>/dev/null' > "$TMP/npm.json"

echo "[3/3] Writing THIRD_PARTY_LICENSES/THIRD_PARTY_NOTICES.md..."
python3 - "$TMP/py.csv" "$TMP/npm.json" > THIRD_PARTY_LICENSES/THIRD_PARTY_NOTICES.md <<'PY'
import csv, io, json, sys
py = list(csv.DictReader(io.StringIO(open(sys.argv[1]).read().strip())))
npm = json.load(open(sys.argv[2]))
COPYLEFT = ("GPL", "MPL", "EPL")
# Packages whose metadata omits the license; verified against their upstream repositories.
OVERRIDES = {"setuptools": "MIT"}
for r in py:
    if r["License"].strip().upper() in ("UNKNOWN", "") and r["Name"] in OVERRIDES:
        r["License"] = OVERRIDES[r["Name"]]
unknown = [r["Name"] for r in py if r["License"].strip().upper() in ("UNKNOWN", "")]
if unknown:
    sys.exit("License unknown for: " + ", ".join(unknown) + " -- add to OVERRIDES after checking upstream")

def row(*c): return "| " + " | ".join(str(x).replace("|", "/") for x in c) + " |"

print("""# Third-party notices

WebReader's own code is MIT licensed (see `LICENSE`). It uses the third-party
software below, each under its own license. This file is generated by
`scripts/generate-notices.sh` from the actual package metadata; do not edit
it by hand. Full license texts ship with the Docker image
(`/app/THIRD_PARTY_LICENSES/python-license-texts.txt`), the desktop release,
and in each package's own distribution.

Tesseract OCR and the bundled fonts are covered in the other files in this
folder (`README.md`, `tesseract-LICENSE-Apache-2.0.txt`, `fonts-licenses.txt`).

## Components with copyleft or weak-copyleft licenses
""")
flag = [r for r in py if any(k in r["License"].upper() for k in COPYLEFT)]
notes = {
  "mobi": "Used to read MOBI/AZW3 files (`backend/utils.py`). GPL-3.0-only: conditions apply when distributing it together with WebReader.",
  "edge-tts": "Run as a separate command-line program for text-to-speech, not linked into WebReader. LGPL-3.0.",
  "certifi": "CA certificate bundle (transitive dependency). MPL-2.0 is file-level copyleft; used unmodified.",
  "tqdm": "Progress bars (transitive dependency). MPL-2.0 / MIT; used unmodified.",
}
print(row("Package", "Version", "License", "How it is used"))
print(row("---", "---", "---", "---"))
for r in flag:
    print(row(r["Name"], r["Version"], r["License"], notes.get(r["Name"], "Transitive dependency; used unmodified.")))
print("""
These notes describe usage only and are not legal advice. If you distribute
WebReader (including as a hosted service), review these licenses for your
situation.

## Python packages (backend image)
""")
print(row("Package", "Version", "License", "URL"))
print(row("---", "---", "---", "---"))
for r in sorted(py, key=lambda r: r["Name"].lower()):
    print(row(r["Name"], r["Version"], r["License"], r["URL"]))
print("\n## JavaScript packages (frontend, production)\n")
print(row("Package", "License", "Repository"))
print(row("---", "---", "---"))
for k, v in sorted(npm.items()):
    if k.startswith("webreader-frontend"): continue
    print(row(k, v.get("licenses", ""), v.get("repository", "")))
print("""
## Machine-learning model

| Model | License | Notes |
|---|---|---|
| microsoft/Florence-2-base | MIT | Optional local image captioning; downloaded on first use unless pre-provisioned. |

## System packages in the Docker image

The image is based on Debian (`python:3.9-slim`) and installs `tesseract-ocr`
(Apache-2.0), `libgl1`, `libglib2.0-0` and `curl`. Each Debian package's
copyright and license file is in `/usr/share/doc/<package>/copyright` inside
the image.

## Windows desktop build only

The desktop `.exe` additionally bundles `pyttsx3`, `pypiwin32`, `pywebview`
and the PyInstaller runtime. Their license texts are included in that
release's `THIRD_PARTY_LICENSES/python-license-texts.txt`.
""")
PY
echo "Done. Review the diff, then commit."
